---
title: "Tutoriel DADA2"
output: github_document
---
Téléchargement de DADA2 :

```{r}
BiocManager::install("dada2", version = "3.18")
library(dada2)

```

Unzip des données :

```{r}
unzip("/Users/azeli/Documents/ADM/Tuto-DADA2/miseqsopdata.zip")
path <- "/Users/azeli/Documents/ADM/Tuto-DADA2/MiSeq_SOP"
list.files(path)
```

Regroupement des forward et reverse :

```{r}
fnFs <- sort(list.files(path, pattern= "_R1_001.fastq", full.names = TRUE))
fnRs <- sort(list.files(path, pattern= "_R2_001.fastq", full.names = TRUE))
sample.names <- sapply(strsplit(basename(fnFs), "_"), `[`, 1)
plotQualityProfile(fnFs[1:2])
```

Graphique représentant les profiles de qualité des séquences forward.

```{r}
plotQualityProfile(fnRs[1:2])
```

Graphique représentant les profiles de qualité des séquences reverse. 

Création d'un nouveau dossier "filtered" dans le directory :

```{r }
filtFs <- file.path(path, "filtered", paste0(sample.names, "_F_filt.fastq.gz"))
filtRs <- file.path(path, "filtered", paste0(sample.names, "_R_filt.fastq.gz"))
names(filtFs) <- sample.names
names(filtRs) <- sample.names

out <- filterAndTrim(fnFs, filtFs, fnRs, filtRs, truncLen=c(240, 160), maxN=0, maxEE=c(2,2), truncQ=2, rm.phix=TRUE)
```




